fix beginner setup/instructions for playground config (#232)
## 📝 Summary

- changes path of `el_node_ipc_path` in `config-playground.toml` to use
`$HOME/.playground/devnet` instead of `/tmp` (aligns with current
builder-playground defaults)
- adds a step in the README to replace '$HOME' with your actual home
path
- `$HOME` was not evaluating correctly for me (tested on my ubuntu
machine), fully-qualified paths fixed it

## 💡 Motivation and Context

Following the
[instructions](https://github.com/flashbots/rbuilder?tab=readme-ov-file#end-to-end-local-testing)
without changing anything gave me this error:

```txt
δ cargo run --bin rbuilder run config-playground.toml
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.67s
     Running `target/debug/rbuilder run config-playground.toml`
...(truncated)

Error: No such file or directory (os error 2)

Caused by:
    No such file or directory (os error 2)

Location:
    /home/dev/code/rbuilder/crates/rbuilder/src/live_builder/order_input/clean_orderpool.rs:30:20
```

The [line of
code](https://github.com/flashbots/rbuilder/blob/develop/crates/rbuilder/src/live_builder/order_input/clean_orderpool.rs#L30)
given by the error connects to the IPC provider, which was being
initialized with an invalid path given the current instructions &
defaults.

## ✅ I have completed the following steps:

* [x] Run `make lint`
* [x] Run `make test`
* [x] Added tests (if applicable)

---------

Co-authored-by: Ferran Borreguero <ferran.borreguero@gmail.com>